from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid
from datetime import datetime

from app.core.database import Base


class NonWorkerIDTask(Base):
    """HR task to generate Non-Worker ID (FR-7, Section 13)."""
    __tablename__ = "non_worker_id_tasks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    referral_id = Column(UUID(as_uuid=True), ForeignKey("referrals.id"), nullable=False, unique=True)
    
    # Task status
    status = Column(String, nullable=False, default="PENDING")  # PENDING, IN_PROGRESS, COMPLETED, FAILED
    
    # Task assignment
    assigned_to = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)  # HR person
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)  # Who created task
    
    # Generated credentials
    generated_non_worker_id = Column(String, nullable=True)  # The actual ID generated by HR system
    credentials_token = Column(String, nullable=True)  # OTP or magic link for secure delivery
    credentials_token_expiry = Column(DateTime, nullable=True)  # Token expires after 24 hours
    
    # SLA tracking (FR-7 & Section 13: SLA ≤ 1 business day)
    sla_deadline = Column(DateTime, nullable=False)  # 1 business day from creation
    sla_breached = Column(Boolean, default=False)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    referral = relationship("Referral", back_populates="non_worker_id_task")
    assignee = relationship("User", foreign_keys=[assigned_to], backref="non_worker_id_tasks_assigned")
    creator = relationship("User", foreign_keys=[created_by], backref="non_worker_id_tasks_created")


# Status constants
TASK_STATUS = {
    "PENDING": "Task created, waiting for HR assignment",
    "IN_PROGRESS": "HR is working on generating ID",
    "COMPLETED": "ID generated and delivered",
    "FAILED": "Failed to generate or deliver ID",
}

# SLA: Non-Worker ID ≤ 1 business day (BRD Section 13)
