from sqlalchemy import Column, String, DateTime, ForeignKey, Text, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid
from sqlalchemy import func
from datetime import datetime

from app.core.database import Base


class WorkflowEvent(Base):
    """Immutable audit log (NFR-4) - All workflow state changes tracked."""
    __tablename__ = "workflow_events"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    referral_id = Column(UUID(as_uuid=True), ForeignKey("referrals.id"), nullable=False)
    
    # Event classification
    event_type = Column(String, nullable=False)  # REFERRAL_CREATED, ELIGIBILITY_PASSED, NDA_SIGNED, etc.
    
    # Event details
    triggered_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)  # Who triggered
    description = Column(Text, nullable=True)  # Human-readable event description
    data = Column(JSON, nullable=True)  # Contextual data: {before: {...}, after: {...}, ...}
    
    # Immutable timestamp (cannot be updated)
    
    timestamp = Column(DateTime, nullable=False, server_default=func.now())
    # Relationships
    referral = relationship("Referral", back_populates="workflow_events")
    actor = relationship("User", foreign_keys=[triggered_by], backref="workflow_events_triggered")


# Valid event types (audit trail coverage)
WORKFLOW_EVENT_TYPES = {
    # Referral lifecycle
    "REFERRAL_CREATED": "New referral submitted",
    "REFERRAL_UPDATED": "Referral data updated",
    "ELIGIBILITY_CHECK_STARTED": "AI eligibility review started",
    "ELIGIBILITY_PASSED": "All eligibility checks passed",
    "ELIGIBILITY_FAILED": "Eligibility check failed",
    "ADMIN_REVIEW_APPROVED": "Referral approved by admin review",
    "ADMIN_REVIEW_REJECTED": "Referral rejected by admin review",
    "ADMIN_REVIEW_CHANGES_REQUESTED": "Admin requested referral changes",
    "MENTOR_REVIEW_APPROVED": "Candidate approved by mentor review",
    "MENTOR_REVIEW_REJECTED": "Candidate rejected by mentor review",
    
    # Joining form
    "JOINING_FORM_CREATED": "Joining form created for candidate",
    "JOINING_FORM_SAVED": "Form draft saved",
    "JOINING_FORM_SUBMITTED": "Joining form submitted by candidate",
    "JOINING_FORM_APPROVED": "Form approved by HR",
    "JOINING_FORM_REJECTED": "Form rejected by HR",
    
    # NDA
    "NDA_ISSUED": "NDA sent to candidate for e-signature",
    "NDA_SIGNED": "NDA signed by candidate",
    "NDA_SIGNATURE_FAILED": "NDA signature failed/rejected",
    "NDA_ARCHIVED": "Signed NDA archived",
    
    # Non-Worker ID
    "NON_WORKER_ID_TASK_CREATED": "Task created for HR",
    "NON_WORKER_ID_GENERATED": "ID generated by HR",
    "CREDENTIALS_SENT": "Credentials/tokens sent to candidate",
    
    # Access provisioning
    "AD_CREDENTIALS_PROVISIONED": "AD account created",
    "ADMIN_ACCESS_GRANTED": "Site/physical access granted",
    
    # Start/Progress
    "INTERNSHIP_STARTED": "Internship officially started",
    "INTERNSHIP_DELAYED": "Start date passed, not started (escalation)",
    "INTERNSHIP_EXTENDED": "End date extended",
    
    # Closure
    "CLOSURE_INITIATED": "Internship closure started",
    "AD_DEPROVISIONED": "AD account deactivated",
    "ADMIN_ACCESS_REVOKED": "Site/physical access revoked",
    "CERTIFICATE_REQUESTED": "Certificate request sent to mentor",
    "CERTIFICATE_GENERATED": "Certificate artifacts generated",
    "CERTIFICATE_ISSUED": "Certificate generated and sent",
    "REFERRAL_CLOSED": "Internship fully closed",
    
    # System events
    "NOTIFICATION_SENT": "System notification dispatched",
    "SYSTEM_ERROR": "System error occurred",
    "MANUAL_OVERRIDE": "Manual override/intervention by staff",
    "SLA_BREACH": "SLA deadline passed",
}

# NFR-4 Audit requirement: All events must be immutable and timestamped
